import "dotenv/config";

export const ENV={
    PORT:process.env.PORT,
    MONGO_URI:process.env.MONGO_URI,
    JWT_SECRET:process.env.JWT_SECRET,
    NODE_ENV:process.env.NODE_ENV,
    MAILTRAP_TOKEN:process.env.MAILTRAP_TOKEN,
    EMAIL_FROM:process.env.EMAIL_FROM,
    EMAIL_NAME:process.env.EMAIL_NAME,
    CLOUDINARY_CLOUD_NAME:process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET:process.env.CLOUDINARY_API_SECRET,
    GOOGLE_CLIENT_ID:process.env.GOOGLE_CLIENT_ID,
    GITHUB_CLIENT_ID:process.env.GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET:process.env.GITHUB_CLIENT_SECRET,
    BACKEND_URL:process.env.BACKEND_URL,
    GITHUB_TOKEN_ENCRYPTION_KEY:process.env.GITHUB_TOKEN_ENCRYPTION_KEY,
    FRONTEND_URL:process.env.FRONTEND_URL,
    NODE_ENV: process.env.NODE_ENV,
};